# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\hauptfenster.ui'
#
# Created: Wed Apr  9 21:09:09 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/pruefe_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBoxKanaeleRechts = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxKanaeleRechts.setGeometry(QtCore.QRect(460, 60, 311, 431))
        self.groupBoxKanaeleRechts.setObjectName("groupBoxKanaeleRechts")
        self.lineEditKanalname = QtGui.QLineEdit(self.groupBoxKanaeleRechts)
        self.lineEditKanalname.setGeometry(QtCore.QRect(10, 350, 291, 20))
        self.lineEditKanalname.setObjectName("lineEditKanalname")
        self.pushButtonHinzufuegen = QtGui.QPushButton(self.groupBoxKanaeleRechts)
        self.pushButtonHinzufuegen.setGeometry(QtCore.QRect(214, 380, 81, 31))
        self.pushButtonHinzufuegen.setObjectName("pushButtonHinzufuegen")
        self.pushButtonLoeschen = QtGui.QPushButton(self.groupBoxKanaeleRechts)
        self.pushButtonLoeschen.setGeometry(QtCore.QRect(244, 310, 51, 23))
        self.pushButtonLoeschen.setObjectName("pushButtonLoeschen")
        self.listWidgetKanaeleRechts = QtGui.QListWidget(self.groupBoxKanaeleRechts)
        self.listWidgetKanaeleRechts.setGeometry(QtCore.QRect(10, 30, 291, 261))
        self.listWidgetKanaeleRechts.setObjectName("listWidgetKanaeleRechts")
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 60, 421, 431))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.label = QtGui.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(50, 140, 311, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButtonPruefen = QtGui.QPushButton(self.page)
        self.pushButtonPruefen.setGeometry(QtCore.QRect(150, 300, 91, 41))
        self.pushButtonPruefen.setIcon(icon)
        self.pushButtonPruefen.setObjectName("pushButtonPruefen")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.progressBar = QtGui.QProgressBar(self.page_2)
        self.progressBar.setGeometry(QtCore.QRect(60, 200, 291, 41))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtGui.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(100, 150, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.pushButtonOeffnen = QtGui.QPushButton(self.page_3)
        self.pushButtonOeffnen.setGeometry(QtCore.QRect(260, 320, 75, 23))
        self.pushButtonOeffnen.setObjectName("pushButtonOeffnen")
        self.listWidgetErgebnis = QtGui.QListWidget(self.page_3)
        self.listWidgetErgebnis.setGeometry(QtCore.QRect(10, 30, 391, 271))
        self.listWidgetErgebnis.setObjectName("listWidgetErgebnis")
        self.stackedWidget.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuDatei = QtGui.QMenu(self.menubar)
        self.menuDatei.setObjectName("menuDatei")
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionPruefen = QtGui.QAction(MainWindow)
        self.actionPruefen.setIcon(icon)
        self.actionPruefen.setObjectName("actionPruefen")
        self.actionBeenden = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/exit_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBeenden.setIcon(icon1)
        self.actionBeenden.setObjectName("actionBeenden")
        self.actionInfo = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/info_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInfo.setIcon(icon2)
        self.actionInfo.setObjectName("actionInfo")
        self.menuDatei.addAction(self.actionPruefen)
        self.menuDatei.addSeparator()
        self.menuDatei.addAction(self.actionBeenden)
        self.menu.addAction(self.actionInfo)
        self.menubar.addAction(self.menuDatei.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.toolBar.addAction(self.actionPruefen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionBeenden)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButtonPruefen, self.lineEditKanalname)
        MainWindow.setTabOrder(self.lineEditKanalname, self.pushButtonHinzufuegen)
        MainWindow.setTabOrder(self.pushButtonHinzufuegen, self.listWidgetKanaeleRechts)
        MainWindow.setTabOrder(self.listWidgetKanaeleRechts, self.pushButtonLoeschen)
        MainWindow.setTabOrder(self.pushButtonLoeschen, self.pushButtonOeffnen)
        MainWindow.setTabOrder(self.pushButtonOeffnen, self.listWidgetErgebnis)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "YouTubeVideoChecker", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxKanaeleRechts.setTitle(QtGui.QApplication.translate("MainWindow", "Kanäle", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditKanalname.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Neuen Kanalnamen hier eingeben.", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonHinzufuegen.setStatusTip(QtGui.QApplication.translate("MainWindow", "Hier klicken um einen neuen Kanal hinzuzufügen.", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonHinzufuegen.setText(QtGui.QApplication.translate("MainWindow", "Hinzufügen", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonLoeschen.setStatusTip(QtGui.QApplication.translate("MainWindow", "Hier klicken um den oben ausgewählten Kanal zu löschen.", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonLoeschen.setText(QtGui.QApplication.translate("MainWindow", "Löschen", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "keine neuen Videos gefunden", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonPruefen.setStatusTip(QtGui.QApplication.translate("MainWindow", "Hier klicken um auf neue Videos zu prüfen.", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonPruefen.setText(QtGui.QApplication.translate("MainWindow", "Alle Prüfen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Suche neue Videos...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOeffnen.setText(QtGui.QApplication.translate("MainWindow", "Öffnen", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDatei.setTitle(QtGui.QApplication.translate("MainWindow", "Datei", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPruefen.setText(QtGui.QApplication.translate("MainWindow", "Prüfen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPruefen.setStatusTip(QtGui.QApplication.translate("MainWindow", "Hier klicken um auf neue Videos zu prüfen.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPruefen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBeenden.setText(QtGui.QApplication.translate("MainWindow", "Beenden", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBeenden.setStatusTip(QtGui.QApplication.translate("MainWindow", "Hier klicken um das Programm zu beenden.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBeenden.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInfo.setText(QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInfo.setStatusTip(QtGui.QApplication.translate("MainWindow", "Hier klicken um Informationen über das Programm zu erhalten.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInfo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+I", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
